version: '3.6'

networks:
  send4-network:
    external: true

services:
  order-api:
    build: .
    volumes:
      - .:/home/node/api
    environment:
      - MONGO_URL=order-mongo
      - REDIS_URL=order-redis
    depends_on:
      - order-mongo
      - order-redis
    networks:
      - send4-network
    links:
      - order-mongo
      - order-redis
    container_name: order-api
    command: yarn dev
    ports:
      - 3002:3002

  order-queue:
    build: .
    volumes:
      - .:/home/node/api
    environment:
      - MONGO_URL=order-mongo
      - REDIS_URL=order-redis
    depends_on:
      - order-mongo
      - order-redis
    networks:
      - send4-network
    links:
      - order-mongo
      - order-redis
    container_name: order-queue
    command: yarn queue

  order-mongo:
    image: bitnami/mongodb:latest
    user: root
    container_name: order-mongo
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_USERNAME=${MONGO_USER}
      - MONGODB_PASSWORD=${MONGO_PASS}
      - MONGODB_DATABASE=${MONGO_DB}
    ports:
      - '27017:27017'
    volumes:
      - /tmp/mongo:/bitnami
    networks:
      - send4-network

  order-redis:
    image: bitnami/redis:latest
    user: root
    container_name: order-redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASS}
    volumes:
      - /tmp/redis:/bitnami/redis/data
    networks:
      - send4-network
